### ISSUE TITLE
@tars/config index.js#132 bug 

### ISSUE THREAD

**Issue by marcellowy** [tars-node/config#2]
### What language are you using?
nodejs
 
### What operating system (Linux, Ubuntu, …) and version?
 linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 none
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

`
var content = iconv.decode(resp.response.arguments.config, "GBK"), format = FORMAT.C;
`
这里的lite-icov会提示错误：Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding

需要将此句改为：
`
var content = iconv.decode(Buffer.from(resp.response.arguments.config), "UTF-8"), format = FORMAT.C;
`
第一个参数已经不可以接受一个String类型，需要使用Buffer
若第一个参数是String将会导致转码失败，并且不可以通过其它的方式进行转码恢复

第二个参数编码的问题，Nodejs默认的编码都是UTF-8，那么我们在编码的时候都是统一使用的UTF-8，当我的 resp.response.arguments.config 为UTF-8时，而上述代码将UTF-8转为了GBK,此时造成原本不会乱码的字符串反而乱码了？

**Comment by medns** [comment]
由于在之前的内部老版本中，config 服务的默认编码格式是 GBK 所以用了 iconv 转换。
开源的 Tars 版本的后台服务已经全部修改为 UTF-8 编码，在这里 Node.js 代码未做变更故导致问题，已经在 @tars/config 新版本中修复。
landed in v2.0.2
